package ChatApp;


/**
* ChatApp/ChatCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Tuesday, February 23, 2016 7:46:29 AM CET
*/

public interface ChatCallbackOperations 
{
  void callback (String message);
} // interface ChatCallbackOperations
