package ChatApp;


/**
* ChatApp/ChatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Tuesday, February 23, 2016 7:46:29 AM CET
*/

public interface ChatOperations 
{
  String say (ChatApp.ChatCallback objref, String message);
  boolean join (ChatApp.ChatCallback objref, String user);
  boolean leave (ChatApp.ChatCallback objref);
  String list (ChatApp.ChatCallback objref);
} // interface ChatOperations
