package ChatApp;


/**
* ChatApp/Chat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Wednesday, February 24, 2016 7:48:54 AM CET
*/

public interface Chat extends ChatOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Chat
